### ISSUE TITLE
Profiler error

### ISSUE THREAD

**Issue by D3strukt0r** [lhapaipai/symfony-vite-dev#40]
### vite-plugin-symfony version

7.0.3

### vite-bundle version

7.0.3

### your OS, node version, Symfony version, PHP version

Debian Docker Container, Node 18.20.4, Symfony 6.4.10, PHP 8.3.10

### Description

I just tried to upgrade from 6.5.0 to 7.0.3 without changing any other config, and now the profiler bar won't load. 

![image](https://github.com/user-attachments/assets/0a61d72f-a5fd-4d64-acd8-2ba3be8bb8c5)

When I check the URL where the 500 happened (https://project.test/_wdt/101c50), I get the error "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "_profiler_vite" as such route does not exist.")."

![image](https://github.com/user-attachments/assets/909ced12-b868-41d2-a326-49e9eb4f93b0)

The profiler URL still works though (https://project.test/_profiler/a9a6f9?panel=pentatrion_vite.vite_collector&type=request)

![image](https://github.com/user-attachments/assets/2c9567bb-585b-4386-bdd6-7f7600f2b204)

### How to reproduce

Dunno, I just updated. Maybe because we are still using Symfony 6.4 for this project?

**Comment by lhapaipai** [comment]
Hi @D3strukt0r,
This is a major version change, this means there may be changes on your part to make

check the [migration v7](https://symfony-vite.pentatrion.com/extra/migration.html#new-route) guide. you have to update the recipe and make updates manually.

**Comment by D3strukt0r** [comment]
ah thanks, sorry didn't see that, i'll close if it worked

**Comment by D3strukt0r** [comment]
Ok worked, thanks :)

but shouldn't that change for the routes/pentatrion_vite.yaml be in the recipes? @lhapaipai

**Comment by lhapaipai** [comment]
the update is in the recipe but indeed. you are in a case where it did not update you.

check the pr : https://github.com/symfony/recipes-contrib/pull/1652

**I had created a temporary version 6.5 just long enough for the pr of the symfony recipe to be accepted so that the recipe would already be merged on the day of v7 (that was the original intention)**. But as a result, it took me longer to release v7, people migrated to v6.5 and although the `config/routes/pentatrion_vite.yaml` file changed between v6.5 and v7, the recipe does not apply a second time. Sorry, I will know for next time

**Comment by jeremyVignelles** [comment]
Thanks for the thread, I faced the same issue today.

Can this issue be pinned for a while so that people like me migrating and wondering could find this more easily ? (I know it's in the migration docs, but it can sometimes be easier to find on the issues page).
